version: '3.3'

services:
  web:
    build: ./
    command: >
      sh -c "python manage.py collectstatic --noinput &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 5433:5432
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgesql/data
    env_file:
      - ./.env

volumes:
  postgres_data:

